#!/bin/bash

docker run -d --name=polyverse_supervisor_1 -v /var/run/docker.sock:/var/run/docker.sock -v $PWD/polyverse.yml:/usr/polyverse.yml polyverse/supervisor:1febb3c6edfdeda0a8de0c0ead1621742a688d83 -config-yaml-file=/usr/polyverse.yml
